FROM python:3.11

RUN apt-get update && apt-get install -y \
    nmap \
    wget \
    unzip \
    golang \
    && rm -rf /var/lib/apt/lists/*

# install nuclei
RUN go install -v github.com/projectdiscovery/nuclei/v3/cmd/nuclei@latest && \
    mv /root/go/bin/nuclei /usr/local/bin/ && \
    nuclei -update-templates

WORKDIR /app
COPY . .

RUN pip install --no-cache-dir -r requirements.txt

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "10000"]

